
name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ walking-skeleton ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run:  dotnet restore './walking-skeleton/walking-skeleton/walking-skeleton.sln'
 
      - name: Build project
        run:  dotnet build './walking-skeleton/walking-skeleton/walking-skeleton.sln'  

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build docker image
        run:  docker build . --file './walking-skeleton/walking-skeleton/Musika/Dockerfile' --tag musika_backend:latest

      - name: Login into docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCTOKEN }} 

      - name: Tag image to repo
        run:  docker tag musika_backend:latest jensevent/musika_backend

      - name: Push image to docker hub
        run:  docker push jensevent/musika_backend
