
name: CI

on:
  push:
    branches: [ walking-skeleton ]

env:
  PATH_TO_SLN: './walking-skeleton/walking-skeleton/walking-skeleton.sln'
  PATH_TO_DOCKERFILE: './walking-skeleton/walking-skeleton/Musika/Dockerfile'
  DOCKER_IMAGE_NAME: musika_backend:latest
  DOCKER_REPO_NAME: jensevent/musika_backend


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run:  dotnet restore $PATH_TO_SLN
 
      - name: Build project
        run:  dotnet build $PATH_TO_SLN  

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run:  dotnet restore $PATH_TO_SLN
 
      - name: Build project
        run:  dotnet build $PATH_TO_SLN

      - name: Test project
        run:  dotnet test --no-restore $PATH_TO_SLN

  docker:
    needs:
      - build
      - test

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build docker image
        run:  docker build . --file $PATH_TO_DOCKERFILE --tag $DOCKER_IMAGE_NAME

      - name: Login into docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCTOKEN }} 

      - name: Tag image to repo
        run:  docker tag $DOCKER_IMAGE_NAME $DOCKER_REPO_NAME

      - name: Push image to docker hub
        run:  docker push $DOCKER_REPO_NAME