name: Development

on:
  push:
    branches: [dev]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["A", "B"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Test
        run : echo ${{matrix.test}}