name: Development

on:
  push:
    branches: [dev]


jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test: [
          {
            PATH_TO_CSPROJ: "abc",
            PATH_TO_TEST_CSPROJ: "CDF"
          },
          {
            object: "def"
          }
        ]
          
    
    steps:
      - uses: actions/checkout@v3

      
      - name: build ${{matrix.test.PATH_TO_CSPROJ}}
        run : echo ${{matrix.test}} 

      - name: test ${{matrix.test.PATH_TO_TEST_CSPROJ}}
        run : echo ${{matrix.test}} 