name: Development

on:
  push:
    branches: [dev]


jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test: [
          {
            PATH_TO_CSPROJ: "./Musika.Backend/Audio.Microservice/Audio.Microservice.csproj",
            PATH_TO_TEST_CSPROJ: "./Musika.Backend/Audio.Microservice.Test/Audio.Microservice.Test.csproj"
          },
          {
            PATH_TO_CSPROJ: "./Musika.Backend/Audio.Microservice/Audio.Microservice.csproj",
            PATH_TO_TEST_CSPROJ: "./Musika.Backend/Audio.Microservice.Test/Audio.Microservice.Test.csproj"
          }
        ]      
    

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/template.yml
        with:
          PATH_TO_CSPROJ: ${{matrix.test.PATH_TO_CSPROJ}},
          PATH_TO_TEST_CSPROJ: ${{matrix.test.PATH_TO_TEST_CSPROJ}}
