name: Development

on:
  push:
    branches: [dev]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["A", "B"]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      
      - name: Test
         run: echo ${{matrix.test}}

