name: Development

on:
  push:
    branches: [dev]


jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test:
          - ["A", "B"]
          - "C"
    
    steps:
      - uses: actions/checkout@v3

      
      - name: Test ${{matrix.test[0]}}
        run : echo ${{matrix.test}} 